### ISSUE TITLE
error in linux when run magneton

### ISSUE THREAD

**Issue by rmnscb** [concretesolutions/magneton#1]
Olá,

Ao correr o magneton em linux, dá o erro abaixo.

Todos os dados do ruby, as gem e o sistema linux abaixo.

Obrigado.

**Error:**

```
guest@guest-VirtualBox:~/testCucumber$ magneton
/var/lib/gems/2.3.0/gems/magneton-0.1.0/bin/magneton:115:in `read': No such file or directory @ rb_sysopen - /usr/share/rubygems-integration/2.3.0/gems/gherkin-2.12.2/lib/gherkin/i18n.json (Errno::ENOENT)
    from /var/lib/gems/2.3.0/gems/magneton-0.1.0/bin/magneton:115:in `initialize'
    from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:355:in `new'
    from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
    from /var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /var/lib/gems/2.3.0/gems/magneton-0.1.0/bin/magneton:137:in `<top (required)>'
    from /usr/local/bin/magneton:22:in `load'
    from /usr/local/bin/magneton:22:in `<main>'
guest@guest-VirtualBox:~/testCucumber$ 
```

**versão do ruby e as gems instaladas:**

```
guest@guest-VirtualBox:~/testCucumber$ ruby -v
ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]
guest@guest-VirtualBox:~/testCucumber$ gem list

*** LOCAL GEMS ***

addressable (2.4.0)
archive-zip (0.8.0, 0.7.0)
aruba (0.14.2)
ast (2.3.0)
backports (3.6.8)
bigdecimal (default: 1.2.8)
blankslate (3.1.3)
builder (3.2.2, 3.0.0)
bundle (0.0.1)
bundler (1.13.1, 1.11.2)
capybara (2.9.1, 2.9.0, 2.5.0, 1.1.4)
capybara-screenshot (1.0.14)
childprocess (0.5.9, 0.5.6)
chromedriver-helper (1.0.0)
clipboard (1.1.1)
cliver (0.3.2)
coderay (1.1.1)
contracts (0.14.0)
cpf_faker (1.3.0)
cucumber (2.4.0, 2.1.0, 2.0.0, 1.1.9)
cucumber-core (2.0.0, 1.5.0, 1.3.0, 1.1.3)
cucumber-wire (0.0.1)
did_you_mean (1.0.2, 1.0.0)
diff-lcs (1.2.5, 1.1.3)
faker (1.6.6)
ffi (1.9.14, 1.9.10, 1.0.11)
gherkin (4.0.0, 2.12.2, 2.9.3)
gherkin3 (3.1.2)
i18n (0.7.0)
io-console (0.4.6, default: 0.4.5)
io-like (0.3.0)
jar_wrapper (0.1.8)
json (2.0.2, default: 1.8.3)
launchy (2.4.3)
magneton (0.1.0)
method_source (0.8.2)
mime-types (3.1, 2.6.2, 2.6.1, 1.17.2)
mime-types-data (3.2016.0521)
mini_portile (0.6.2)
mini_portile2 (2.1.0)
minitest (5.9.1, 5.9.0, 5.8.4)
molinillo (0.5.1, 0.4.3)
multi_json (1.12.1, 1.11.2, 1.0.4)
multi_test (0.1.2)
net-http-persistent (2.9.4)
net-telnet (0.1.1)
nokogiri (1.6.8, 1.6.7.2, 1.6.6.2)
oj (2.17.4, 2.12.10)
parser (2.3.1.4)
pkg-config (1.1.7)
poltergeist (1.10.0)
power_assert (0.3.1, 0.2.7)
powerpack (0.1.1)
pry (0.10.4)
pry-nav (0.2.4)
psych (2.1.1, default: 2.0.17)
rack (2.0.1, 1.6.4, 1.4.0)
rack-test (0.6.3)
rainbow (2.1.0)
rake (11.3.0, 10.5.0)
rdoc (4.2.2, default: 4.2.1)
rspec (3.5.0, 2.8.0)
rspec-core (3.5.3, 2.8.0)
rspec-expectations (3.5.0, 2.8.0)
rspec-mocks (3.5.0, 2.8.0)
rspec-support (3.5.0)
rubocop (0.43.0)
ruby-progressbar (1.8.1)
rubygems-update (2.6.7)
rubyzip (1.2.0, 1.1.7, 0.9.5)
selenium (0.2.11)
selenium-webdriver (2.53.4, 2.48.0)
site_prism (2.9)
slop (4.4.1, 3.6.0)
syntax (1.2.1)
term-ansicolor (1.4.0, 1.3.2, 1.0.7)
test-unit (3.2.1, 3.1.7)
thor (0.19.1)
tins (1.12.0)
unicode-display_width (1.1.1)
websocket (1.2.3, 1.2.2)
websocket-driver (0.6.4)
websocket-extensions (0.1.2)
xpath (2.0.0, 0.1.4)
zip (2.0.2)
```

**versão do linux utilizada:**

```
guest@guest-VirtualBox:uname -a
Linux guest-VirtualBox 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by mondaini** [comment]
Fiz um teste aqui e não consegui simular o problema ainda. Vou dar uma olhada mais a fundo depois. 

```
➜  cucumber-capybara-site_prism git:(novos_testes) ✗ gem install magneton
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: gherkin-2.12.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed gherkin-2.12.2
Fetching: magneton-0.1.0.gem (100%)
Successfully installed magneton-0.1.0
Parsing documentation for thor-0.19.1
Installing ri documentation for thor-0.19.1
Parsing documentation for gherkin-2.12.2
Installing ri documentation for gherkin-2.12.2
Parsing documentation for magneton-0.1.0
Installing ri documentation for magneton-0.1.0
Done installing documentation for thor, gherkin, magneton after 35 seconds
3 gems installed
➜  cucumber-capybara-site_prism git:(novos_testes) ✗ magneton
Commands:
  magneton g [GENERATOR] [RESOURCE_NAME]         # Generates various resources
  magneton generate [GENERATOR] [RESOURCE_NAME]  # Generates various resources
  magneton help [COMMAND]                        # Describe available commands or one specific command
  magneton new PROJECT_NAME                      # Generates the structure of a new project that uses Capybara, SitePrism, Selenium and Cucumber
  magneton version                               # Shows the gem version

➜  cucumber-capybara-site_prism git:(novos_testes) ✗ 
```

**Comment by rmnscb** [comment]
Depois de apagar a maquina virtual e instalar tudo de novo, o erro já não acontece.

Muito Obrigado :)

**Comment by samycici** [comment]
Obrigada pelo feedback @rmnscb :)
